services:
  - type: web
    name: tcdd-frontend
    env: node
    rootDir: tcdd-ui/frontend/frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_BASE
        value: https://<senin-api-url>.onrender.com
